##  Named of the workflow.
name: Docker build
## Set the trigger policy.
## In this case, the workflow is execute on a `push` event,
## or when a new commit is pushed to the repository
on: [push]
## List the steps to be executed by the workflow
jobs:
  ## Set the name of the job
  docker-build:
    ## Configure the operating system the workflow should run on.
    ## In this case, the job on Ubuntu
    runs-on: ubuntu-latest
    ## Define a sequence of steps to be executed 
    steps:
      ## Build the Python Helloworld image
      - run: docker build -t python-helloworld GITHUB_ACTION_PATH/../../exercises/python-helloworld
      ## Push that image to Docker hub 
      - run: docker push daveroye/python-helloworld:v1.0.0
